# Generated by Django 5.1.3 on 2025-05-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('record_id', models.IntegerField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deleted_records',
            },
        ),
        migrations.AddField(
            model_name='form_columns',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
