# Generated by Django 5.1.3 on 2025-05-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_deletion_form_columns_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
