"""
Django settings for customadmin project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/



import os
from decouple import config

SECRET_KEY = config('SECRET_KEY')  # No default! Force to be set.

RETELL_API_KEY = config('RETELL_API_KEY', default='')
VOICEFLOW_API_KEY = config('VOICEFLOW_API_KEY', default='')
RETELL_PHONE = config('RETELL_PHONE', default='')

DEBUG = config('DEBUG', default=False, cast=bool)

# Add to ALLOWED_HOSTS for ngrok
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '143.110.247.53','voiceai.codedock.site','*']

# Add your ngrok domain to trusted origins
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_ALL_ORIGINS = True # If this is used then `CORS_ALLOWED_ORIGINS` will not have any effect
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    'https://retell-voice-assitant.onrender.com',
]
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'retells',  # use the config class'django_apscheduler',
    'AI_Assistant.apps.AI_AssistantConfig',
    'FastPromos'

]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'customadmin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'customadmin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import dj_database_url

DATABASE_URL = config('DATABASE_URL', default='sqlite:///db.sqlite3')

DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL)
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # This line tells Django to look in the static/ folder
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10  # ✅ Only 10 per page
}

JAZZMIN_SETTINGS = {
    "site_title": "Voice Assistant Admin",
    "site_brand": "Voice Assistant",
    "site_header": "Voice Assistant",
    "welcome_sign": "Welcome to your Admin Portal",
    "site_logo": 'logo/logo.png',
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Voice Assistant",
    "copyright": "Voice Assistant Ltd",
    # Whether to display the side menu
    "show_sidebar": True,
    "custom_links": {
        "retells": [{
            "name": "Agents",
            "url": "/retells/agents/",
            "icon": "fas fa-robot",
        }],
        "ai_assistant": [
        # {
        #     "name": "custom-llm",
        #     "url": "custom_llm",
        #     "icon": "fas fa-robot",
        # },
        # {
        #     "name": "AI_Assistant-knowledgebase",
        #     "url": "knowledgebase",
        #     "icon": "fas fa-robot",
        # },
        {
            "name": "Chat Assistant Demo",
            "url": "chatbot",
            "icon": "fas fa-robot",
        },
        {
            "name": "Add FAQ",
            "url": "add_faqs",
            "icon": "fas fa-robot",
        }]
    },
    "custom_css": "admin/css/admin_custom.css",
    "hide_apps": ['auth','retells'],
# Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,
    
    # ChangeForm customizations
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    
    # Language chooser
    "language_chooser": False,
}
