# Generated by Django 5.2.1 on 2025-07-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FastPromos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productdetails',
            options={'verbose_name': 'Product Details', 'verbose_name_plural': 'Product Details'},
        ),
    ]
