# Generated by Django 5.1.3 on 2025-05-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
