# Generated by Django 5.2.1 on 2025-07-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_Assistant', '0002_chathistory_chatuser_delete_dummy_chathistory_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chathistory',
            options={'verbose_name': 'Chat History', 'verbose_name_plural': 'Chat History'},
        ),
        migrations.AlterModelOptions(
            name='chatuser',
            options={'verbose_name': 'Chat User', 'verbose_name_plural': 'Chat User'},
        ),
    ]
