# Generated by Django 5.2.1 on 2025-07-05 12:53

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter the full number in international format (e.g., +919876543210)', max_length=128, region=None, unique=True)),
                ('call_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted')], default='NEW', max_length=20)),
                ('call_outcome', models.CharField(blank=True, choices=[('user_hangup', 'User hangup'), ('agent_hangup', 'Agent hangup'), ('call_transfer', 'Call transferred'), ('voicemail_reached', 'Voicemail reached'), ('inactivity', 'Inactivity timeout'), ('machine_detected', 'Machine detected'), ('max_duration_reached', 'Max duration reached'), ('concurrency_limit_reached', 'Concurrency limit reached'), ('no_valid_payment', 'No valid payment'), ('scam_detected', 'Scam detected'), ('error_inbound_webhook', 'Inbound webhook error'), ('dial_busy', 'Dial busy'), ('dial_failed', 'Dial failed'), ('dial_no_answer', 'Dial no answer'), ('error_llm_websocket_open', 'LLM websocket open error'), ('error_llm_websocket_lost_connection', 'LLM websocket lost'), ('error_llm_websocket_runtime', 'LLM websocket runtime error'), ('error_llm_websocket_corrupt_payload', 'LLM corrupt payload'), ('error_no_audio_received', 'No audio received'), ('error_asr', 'ASR error'), ('error_retell', 'Retell internal error'), ('error_unknown', 'Unknown error'), ('error_user_not_joined', 'User didn’t join web call'), ('registered_call_timeout', 'Registered call timeout')], help_text='Detailed Retell call outcome', max_length=50, null=True)),
                ('agent_id', models.CharField(blank=True, help_text='Retell AI Agent ID', max_length=255)),
                ('agent_name', models.CharField(blank=True, max_length=255)),
                ('call_now', models.BooleanField(default=False, help_text='Check this to initiate the call immediately.')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome_tag', models.JSONField(blank=True, help_text="Short outcome summary like 'Interested', 'Wrong number', 'No interest'", null=True)),
                ('call_rating', models.IntegerField(blank=True, help_text='Call rating from 1 to 5, or 0 if not applicable', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('call_retry', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('direction', models.CharField(default='outbound', max_length=20)),
                ('call_id', models.CharField(help_text='Retell API Call ID', max_length=255, unique=True)),
                ('agent_id', models.CharField(blank=True, help_text='Retell Agent ID', max_length=255)),
                ('call_status', models.CharField(default='ongoing', max_length=50)),
                ('call_successful', models.CharField(max_length=20)),
                ('disconnection_reason', models.CharField(max_length=20)),
                ('user_sentiment', models.CharField(max_length=20)),
                ('duration', models.PositiveBigIntegerField(blank=True, help_text='Call duration', null=True)),
                ('transcript', models.TextField(blank=True, help_text='Call transcript from Retell')),
                ('outcome_tag', models.JSONField(blank=True, help_text="Short outcome summary like 'Interested', 'Wrong number', 'No interest'", null=True)),
                ('call_rating', models.IntegerField(blank=True, help_text='Call rating from 1 to 5, or 0 if not applicable', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('recording_url', models.URLField(blank=True, help_text='URL to call recording')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_history', to='retells.lead')),
            ],
            options={
                'verbose_name': 'Call History',
                'verbose_name_plural': 'Call History',
            },
        ),
    ]
