# Generated by Django 5.2.1 on 2025-06-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='property_interest',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
    ]
