# Generated by Django 5.2.1 on 2025-06-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0002_remove_lead_email_remove_lead_property_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('direction', models.CharField(default='outbound', max_length=20)),
                ('call_id', models.CharField(help_text='Retell API Call ID', max_length=100, unique=True)),
                ('retell_call_id', models.CharField(blank=True, help_text='Retell internal call ID', max_length=100)),
                ('call_status', models.CharField(max_length=20)),
                ('call_successful', models.CharField(max_length=20)),
                ('disconnection_reason', models.CharField(max_length=20)),
                ('user_sentiment', models.CharField(max_length=20)),
                ('transcript', models.TextField(blank=True, help_text='Call transcript from Retell')),
                ('recording_url', models.URLField(blank=True, help_text='URL to call recording')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_history', to='retells.lead')),
            ],
        ),
    ]
