# Generated by Django 5.2.1 on 2025-06-02 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0004_alter_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_call_id', models.CharField(help_text='Retell Batch Call ID', max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('from_number', models.CharField(max_length=20)),
                ('scheduled_timestamp', models.CharField(max_length=20)),
                ('recipients', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='callhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='callhistory',
            name='batch_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_call_histories', to='retells.batchcall'),
        ),
    ]
