# Generated by Django 5.2.1 on 2025-06-03 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0005_batchcall_callhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcall',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='batchcall',
            name='batch_call_id',
            field=models.CharField(help_text='Retell batch call ID', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='batchcall',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='batchcall',
            name='recipients',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batchcall',
            name='scheduled_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='batchcall',
            name='status',
            field=models.CharField(default='ongoing', max_length=50),
        ),
        migrations.AlterField(
            model_name='callhistory',
            name='call_id',
            field=models.CharField(help_text='Retell API Call ID', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='callhistory',
            name='call_status',
            field=models.CharField(default='ongoing', max_length=50),
        ),
        migrations.AlterField(
            model_name='callhistory',
            name='retell_call_id',
            field=models.CharField(blank=True, help_text='Retell internal call ID', max_length=255),
        ),
    ]
