# Generated by Django 5.2.1 on 2025-06-04 03:31

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0008_alter_lead_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcall',
            name='included_leads',
            field=models.ManyToManyField(blank=True, related_name='batch_calls', to='retells.lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter the full number in international format (e.g., +919876543210)', max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ONGOING', 'Ongoing'), ('CONTACTED', 'Contacted'), ('UNREACHABLE', 'Unreachable')], default='NEW', max_length=20),
        ),
    ]
