# Generated by Django 5.2.1 on 2025-06-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0009_batchcall_included_leads_alter_lead_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callhistory',
            name='batch_call',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='status',
            new_name='call_status',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='name',
            new_name='lead_name',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='lead',
            name='agent',
            field=models.CharField(blank=True, help_text='Retell AI Agent ID', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='BatchCall',
        ),
    ]
