# Generated by Django 5.2.1 on 2025-06-04 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0011_callhistory_duration_ms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callhistory',
            old_name='duration_ms',
            new_name='duration',
        ),
    ]
