# Generated by Django 5.2.1 on 2025-06-05 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0012_rename_duration_ms_callhistory_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='agent',
        ),
        migrations.AddField(
            model_name='lead',
            name='agent_id',
            field=models.CharField(blank=True, help_text='Retell AI Agent ID', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='scheduled_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 5, 10, 9, 25, 493647)),
            preserve_default=False,
        ),
    ]
