# Generated by Django 5.2.1 on 2025-06-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0014_lead_call_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
