# Generated by Django 5.2.1 on 2025-06-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0016_lead_call_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='call_status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted')], default='NEW', max_length=20),
        ),
    ]
