# Generated by Django 5.2.1 on 2025-06-05 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0017_alter_lead_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_rating',
            field=models.IntegerField(blank=True, help_text='Call rating from 1 to 5, or 0 if not applicable', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='lead',
            name='outcome_tag',
            field=models.CharField(blank=True, help_text="Short outcome summary like 'Interested', 'Wrong number', 'No interest'", max_length=255),
        ),
    ]
