# Generated by Django 5.2.1 on 2025-06-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0018_lead_call_rating_lead_outcome_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='outcome_tag',
            field=models.JSONField(blank=True, help_text="Short outcome summary like 'Interested', 'Wrong number', 'No interest'", null=True),
        ),
    ]
