# Generated by Django 5.2.1 on 2025-06-05 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0019_alter_lead_outcome_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistory',
            name='call_rating',
            field=models.IntegerField(blank=True, help_text='Call rating from 1 to 5, or 0 if not applicable', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='callhistory',
            name='outcome_tag',
            field=models.JSONField(blank=True, help_text="Short outcome summary like 'Interested', 'Wrong number', 'No interest'", null=True),
        ),
    ]
