# Generated by Django 5.2.1 on 2025-06-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0020_callhistory_call_rating_callhistory_outcome_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistory',
            name='duration',
            field=models.PositiveBigIntegerField(blank=True, help_text='Call duration', null=True),
        ),
    ]
