# Generated by Django 5.2.1 on 2025-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retells', '0021_alter_callhistory_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='call_retry',
            field=models.IntegerField(default=0),
        ),
    ]
